language: scala
script:
  - sbt ++$TRAVIS_SCALA_VERSION clean update compile test package publishOnlyWhenOnMaster
scala:
  - 2.11.0-RC3
jdk:
  - openjdk6
  - openjdk7
  - oraclejdk8
notifications:
  email:
    - eugene.burmako@epfl.ch
    - denys.shabalin@typesafe.com
env:
  global:
   - SCALAREFLECT_MAVEN_REALM="Sonatype Nexus Repository Manager"
   - SCALAREFLECT_MAVEN_DOMAIN="oss.sonatype.org"
   - secure: "K/3fAp6sFxSKeVAh8HtTXB8CjJgwZTmZLPoznqUhiC2Vu8pX+msyxgiJoaTA1IsDsacmpZswhiq8d/GC7ytW3VugckgWjyHUIv8OEeVTeypkkUUyP9jGFnAX1aGVjvFWbVuJAsPScxIo1DkV1flXUNDtwJdm/Bu4GHsEm2kWHF4="
   - secure: "YFAmoOcLjhlwuwTg3fmCoJDXYArV7F2maqDE0WaVWNyVQOiFFLJ6ySG/V7yi97nhDnETUL4dZKEq/M5cyOScgS7UbDb9yhTP6vwwxE8SnkXZZy+5Kv/46Kb6FHfMZ3QO2TRbGYtHS2FNS2r5cnipZoi5AKOhoy4nAXgB9EKcd7I="
